# A linha &#39;version&#39; foi removida, conforme a recomendação da documentação oficial do Docker 

services:
  db:
    image: postgres:15-alpine # Usar uma versão específica como '15-alpine' é melhor que 'latest'
    container_name: fifo_db_container
    restart: always
    # As variáveis são lidas do .env e injetadas no ambiente do contentor
    env_file:
    - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # HEALTHCHECK: Garante que o banco de dados esteja realmente pronto para aceitar conexões
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:2025-07-23-1
    container_name: pgadmin_fifo
    env_file:
      - .env
    ports:
      - "5050:80" # Acessível em http://localhost:5050
    depends_on:
      - db
    restart: always

  backend:
    container_name: fifo_backend_container
    build: ./backend
    restart: always
    ports:
      - "8080:8080"
            # O Docker Compose irá procurar um ficheiro .env na pasta do backend 
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  frontend:
    container_name: fifo_frontend_container
    build: ./frontend
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  postgres_data: