
services:
  backend:
    container_name: fifo_backend
    build: 
      context: ./backend # Aponta para a pasta do projeto Java
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env # Lê as configurações específicas do Java

  frontend:
    container_name: fifo_frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5173:80" # Mapeia a porta 80 do Nginx para 5173 (padrão do seu dev)
    depends_on:
      - backend